# Generated by Django 4.0.4 on 2022-07-18 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websiterecord',
            name='job_id',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
