# Generated by Django 4.0.4 on 2022-07-18 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='boundary_record',
            field=models.BooleanField(default=False),
        ),
    ]
