# Generated by Django 4.0.4 on 2022-07-02 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='website_record',
        ),
        migrations.AddField(
            model_name='tag',
            name='website_record',
            field=models.ManyToManyField(to='api.websiterecord'),
        ),
    ]
