# Generated by Django 4.0.4 on 2022-07-02 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_tag_website_record_tag_website_record'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='website_record',
        ),
        migrations.AddField(
            model_name='websiterecord',
            name='tags',
            field=models.ManyToManyField(to='api.tag'),
        ),
    ]
