# Generated by Django 4.0.4 on 2022-07-02 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_tag_website_record_websiterecord_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='websiterecord',
            name='status',
        ),
        migrations.AddField(
            model_name='websiterecord',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
