# Generated by Django 4.0.4 on 2022-07-02 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_websiterecord_status_websiterecord_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='node',
            old_name='domain',
            new_name='crawl_time',
        ),
        migrations.RenameField(
            model_name='node',
            old_name='website_record',
            new_name='owner',
        ),
        migrations.AddField(
            model_name='node',
            name='title',
            field=models.CharField(max_length=2048, null=True),
        ),
    ]
