# Generated by Django 4.0.4 on 2022-07-06 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_domain_node_crawl_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='execution',
            name='crawl_time',
        ),
        migrations.AddField(
            model_name='execution',
            name='crawl_duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='execution',
            name='last_crawl',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='execution',
            name='status',
            field=models.IntegerField(default=4),
        ),
    ]
