# Generated by Django 4.0.4 on 2022-07-16 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_execution_crawl_time_execution_crawl_duration_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='websiterecord',
            options={'ordering': ('url', 'interval')},
        ),
    ]
