name: Backend Docker Image - Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Docker build Frontend
      run: docker build -f ./frontend/Dockerfile ./frontend/
